name: CI

on: [push, pull_request]

jobs:
  # Use the following command to fix words locally:
  # codespell --ignore-words-list "crate" --skip "*/target" --write-changes
  check-spelling:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - name: Check spelling
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: "crate"
          skip: "*/target"

  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        run: cargo fmt --all -- --check

  tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          toolchain: stable
          target: i686-unknown-linux-gnu
        - os: ubuntu-latest
          toolchain: stable
          target: x86_64-unknown-linux-gnu
        - os: ubuntu-latest
          toolchain: beta
          target: i686-unknown-linux-gnu
        - os: ubuntu-latest
          toolchain: beta
          target: x86_64-unknown-linux-gnu
        - os: ubuntu-latest
          toolchain: nightly
          target: i686-unknown-linux-gnu
        - os: ubuntu-latest
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
        - os: macos-latest
          toolchain: stable
          target: x86_64-apple-darwin
        - os: macos-latest
          toolchain: stable
          target: x86_64-apple-ios
        - os: macos-latest
          toolchain: beta
          target: x86_64-apple-darwin
        - os: macos-latest
          toolchain: beta
          target: x86_64-apple-ios
        - os: macos-latest
          toolchain: nightly
          target: x86_64-apple-darwin
        - os: macos-latest
          toolchain: nightly
          target: x86_64-apple-ios
        - os: windows-latest
          toolchain: stable-msvc
          target: i686-pc-windows-msvc
        - os: windows-latest
          toolchain: stable-msvc
          target: x86_64-pc-windows-msvc
        - os: windows-latest
          toolchain: beta-msvc
          target: i686-pc-windows-msvc
        - os: windows-latest
          toolchain: beta-msvc
          target: x86_64-pc-windows-msvc
        - os: windows-latest
          toolchain: nightly-msvc
          target: i686-pc-windows-msvc
        - os: windows-latest
          toolchain: nightly-msvc
          target: x86_64-pc-windows-msvc
        - os: windows-latest
          toolchain: stable-gnu
          target: i686-pc-windows-gnu
        - os: windows-latest
          toolchain: stable-gnu
          target: x86_64-pc-windows-gnu
        - os: windows-latest
          toolchain: beta-gnu
          target: i686-pc-windows-gnu
        - os: windows-latest
          toolchain: beta-gnu
          target: x86_64-pc-windows-gnu
        - os: windows-latest
          toolchain: nightly-gnu
          target: i686-pc-windows-gnu
        - os: windows-latest
          toolchain: nightly-gnu
          target: x86_64-pc-windows-gnu
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions-rs/toolchain@v1
        name: Install toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          override: true
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --all
      - name: Test
        run: cargo test --verbose --all -- --nocapture
      - name: Generate docs
        run: cargo doc

  valgrind:
    name: Valgrind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install valgrind
        run: sudo apt-get install valgrind
      - name: Install cargo-valgrind
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-valgrind
          version: latest
      - name: Run valgrind tests
        run: cargo valgrind test

  lints:
    name: Clippy lints
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: actions/checkout@v2
      - name: Check for lints
        run: cargo clippy -- -D warnings
      - name: Check for test lints
        run: cargo clippy --tests -- -D warnings
